### ISSUE TITLE
After latest update, the controller won't start. 

### ISSUE THREAD

**Issue by EeroV** [gozoinks/unifi-pfsense#156]
errorlogs from mongodb:

----- BEGIN BACKTRACE -----
{"backtrace":[{"b":"1021000","o":"12F70A9","s":"_ZN5mongo15printStackTraceERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEE"},{"b":"1021000","o":"12F68DB","s":"_ZN5mongo29reportOutOfMemoryErrorAndExitEv"},{"b":"8071A7000","o":"E946","s":"pthread_sigmask"},{"b":"8071A7000","o":"DEB2","s":"pthread_getspecific"}],"processInfo":{ "mongodbVersion" : "3.4.21", "gitVersion" : "ba2e818de44c9a331ce09a624780a2bd841cf6e4", "compiledModules" : [], "uname" : { "sysname" : "FreeBSD", "release" : "11.2-RELEASE-p10", "version" : "FreeBSD 11.2-RELEASE-p10 #9 4a2bfdce133(RELENG_2_4_4): Wed May 15 18:54:42 EDT 2019     root@buildbot1-nyi.netgate.com:/build/ce-crossbuild-244/obj/amd64/ZfGpH5cd/build/ce-crossbuild-244/pfSense/tmp/FreeBSD-src/sys/pfSense", "machine" : "amd64" } }}
 mongod(_ZN5mongo15printStackTraceERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEE+0x39) [0x23180a9]
 mongod(_ZN5mongo29reportOutOfMemoryErrorAndExitEv+0x15B) [0x23178db]
 libthr.so.3(pthread_sigmask+0x536) [0x8071b5946]
 libthr.so.3(pthread_getspecific+0xE12) [0x8071b4eb2]
-----  END BACKTRACE  -----
2019-09-08T10:57:28.518+0300 I CONTROL  [main] ***** SERVER RESTARTED *****
2019-09-08T10:57:28.535+0300 I CONTROL  [initandlisten] MongoDB starting : pid=28371 port=27117 dbpath=/usr/local/UniFi/data/db 64-bit host=pfSense.localdomain
2019-09-08T10:57:28.536+0300 I CONTROL  [initandlisten] db version v3.4.21
2019-09-08T10:57:28.536+0300 I CONTROL  [initandlisten] git version: ba2e818de44c9a331ce09a624780a2bd841cf6e4
2019-09-08T10:57:28.536+0300 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2o-freebsd  27 Mar 2018
2019-09-08T10:57:28.536+0300 I CONTROL  [initandlisten] allocator: system
2019-09-08T10:57:28.536+0300 I CONTROL  [initandlisten] modules: none
2019-09-08T10:57:28.536+0300 I CONTROL  [initandlisten] build environment:
2019-09-08T10:57:28.536+0300 I CONTROL  [initandlisten]     distarch: x86_64
2019-09-08T10:57:28.536+0300 I CONTROL  [initandlisten]     target_arch: x86_64
2019-09-08T10:57:28.536+0300 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 27117, unixDomainSocket: { pathPrefix: "/usr/local/UniFi/run" } }, storage: { dbPath: "/usr/local/UniFi/data/db" }, systemLog: { destination: "file", logAppend: true, path: "/usr/local/UniFi/logs/mongod.log" } }
2019-09-08T10:57:28.537+0300 I -        [initandlisten] Detected data files in /usr/local/UniFi/data/db created by the 'mmapv1' storage engine, so setting the active storage engine to 'mmapv1'.
2019-09-08T10:57:28.558+0300 I JOURNAL  [initandlisten] journal dir=/usr/local/UniFi/data/db/journal
2019-09-08T10:57:28.558+0300 I JOURNAL  [initandlisten] recover begin
2019-09-08T10:57:28.558+0300 I JOURNAL  [initandlisten] info no lsn file in journal/ directory
2019-09-08T10:57:28.558+0300 I JOURNAL  [initandlisten] recover lsn: 0
2019-09-08T10:57:28.558+0300 I JOURNAL  [initandlisten] recover /usr/local/UniFi/data/db/journal/j._0
2019-09-08T10:57:28.558+0300 I JOURNAL  [initandlisten] recover applying initial journal section with sequence number 154
2019-09-08T10:57:28.562+0300 I JOURNAL  [initandlisten] recover cleaning up
2019-09-08T10:57:28.563+0300 I JOURNAL  [initandlisten] removeJournalFiles
2019-09-08T10:57:28.563+0300 I JOURNAL  [initandlisten] old journal file will be removed: /usr/local/UniFi/data/db/journal/j._0
2019-09-08T10:57:28.563+0300 I JOURNAL  [initandlisten] recover done
2019-09-08T10:57:28.587+0300 I JOURNAL  [durability] Durability thread started
2019-09-08T10:57:28.587+0300 I CONTROL  [initandlisten] 
2019-09-08T10:57:28.587+0300 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2019-09-08T10:57:28.587+0300 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2019-09-08T10:57:28.587+0300 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2019-09-08T10:57:28.587+0300 I CONTROL  [initandlisten] 
2019-09-08T10:57:28.587+0300 I CONTROL  [initandlisten] 
2019-09-08T10:57:28.587+0300 I JOURNAL  [journal writer] Journal writer thread started
2019-09-08T10:57:28.587+0300 I CONTROL  [initandlisten] ** WARNING: soft rlimits too low. rlimits set to 8470 processes, 115731 files. Number of processes should be at least 57865.5 : 0.5 times number of files.
2019-09-08T10:57:28.619+0300 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/usr/local/UniFi/data/db/diagnostic.data'
2019-09-08T10:57:28.624+0300 I NETWORK  [thread1] waiting for connections on port 27117
2019-09-08T10:57:30.277+0300 I NETWORK  [thread1] connection accepted from 127.0.0.1:26081 #1 (1 connection now open)
2019-09-08T10:57:30.286+0300 I -        [conn1] end connection 127.0.0.1:26081 (1 connection now open)
2019-09-08T10:57:30.659+0300 I NETWORK  [thread1] connection accepted from 127.0.0.1:55805 #2 (1 connection now open)
2019-09-08T10:57:30.666+0300 I NETWORK  [conn2] received client metadata from 127.0.0.1:55805 conn2: { driver: { name: "mongo-java-driver", version: "3.4.3-dirty" }, os: { type: "unknown", name: "FreeBSD", architecture: "amd64", version: "11.2-RELEASE-p10" }, platform: "Java/Oracle Corporation/1.8.0_222-b10" }
2019-09-08T10:57:30.708+0300 I NETWORK  [thread1] connection accepted from 127.0.0.1:17719 #3 (2 connections now open)
2019-09-08T10:57:30.709+0300 I NETWORK  [conn3] received client metadata from 127.0.0.1:17719 conn3: { driver: { name: "mongo-java-driver", version: "3.4.3-dirty" }, os: { type: "unknown", name: "FreeBSD", architecture: "amd64", version: "11.2-RELEASE-p10" }, platform: "Java/Oracle Corporation/1.8.0_222-b10" }
2019-09-08T10:57:30.998+0300 I NETWORK  [thread1] connection accepted from 127.0.0.1:35276 #4 (3 connections now open)
2019-09-08T10:57:30.999+0300 I NETWORK  [conn4] received client metadata from 127.0.0.1:35276 conn4: { driver: { name: "mongo-java-driver", version: "3.4.3-dirty" }, os: { type: "unknown", name: "FreeBSD", architecture: "amd64", version: "11.2-RELEASE-p10" }, platform: "Java/Oracle Corporation/1.8.0_222-b10" }
2019-09-08T10:57:31.024+0300 I NETWORK  [thread1] connection accepted from 127.0.0.1:40145 #5 (4 connections now open)
2019-09-08T10:57:31.025+0300 I NETWORK  [conn5] received client metadata from 127.0.0.1:40145 conn5: { driver: { name: "mongo-java-driver", version: "3.4.3-dirty" }, os: { type: "unknown", name: "FreeBSD", architecture: "amd64", version: "11.2-RELEASE-p10" }, platform: "Java/Oracle Corporation/1.8.0_222-b10" }
2019-09-08T10:57:31.172+0300 I STORAGE  [conn5] _getOpenFile() invalid file index requested 1
2019-09-08T10:57:31.172+0300 I -        [conn5] Invariant failure false src/mongo/db/storage/mmap_v1/mmap_v1_extent_manager.cpp 207
2019-09-08T10:57:31.172+0300 I -        [conn5] 

***aborting after invariant() failure

2019-09-08T10:57:31.173+0300 F -        [conn5] Got signal: 6 (Abort trap).

 0x23180a9 0x23178db 0x8071b5946 0x8071b4eb2
----- BEGIN BACKTRACE -----
{"backtrace":[{"b":"1021000","o":"12F70A9","s":"_ZN5mongo15printStackTraceERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEE"},{"b":"1021000","o":"12F68DB","s":"_ZN5mongo29reportOutOfMemoryErrorAndExitEv"},{"b":"8071A7000","o":"E946","s":"pthread_sigmask"},{"b":"8071A7000","o":"DEB2","s":"pthread_getspecific"}],"processInfo":{ "mongodbVersion" : "3.4.21", "gitVersion" : "ba2e818de44c9a331ce09a624780a2bd841cf6e4", "compiledModules" : [], "uname" : { "sysname" : "FreeBSD", "release" : "11.2-RELEASE-p10", "version" : "FreeBSD 11.2-RELEASE-p10 #9 4a2bfdce133(RELENG_2_4_4): Wed May 15 18:54:42 EDT 2019     root@buildbot1-nyi.netgate.com:/build/ce-crossbuild-244/obj/amd64/ZfGpH5cd/build/ce-crossbuild-244/pfSense/tmp/FreeBSD-src/sys/pfSense", "machine" : "amd64" } }}
 mongod(_ZN5mongo15printStackTraceERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEE+0x39) [0x23180a9]
 mongod(_ZN5mongo29reportOutOfMemoryErrorAndExitEv+0x15B) [0x23178db]
 libthr.so.3(pthread_sigmask+0x536) [0x8071b5946]
 libthr.so.3(pthread_getspecific+0xE12) [0x8071b4eb2]
-----  END BACKTRACE  -----
[2.4.4-RELEASE][admin@pfSense.localdomain]/usr/local/UniFi/logs: 

how to fix issue?

**Comment by EeroV** [comment]
and from server.log

[2019-09-08T10:29:00,467] <launcher> INFO  system - ======================================================================
[2019-09-08T10:29:00,484] <launcher> INFO  system - UniFi 5.10.26 (build atag_5.10.26_11685 - release) is started
[2019-09-08T10:29:00,484] <launcher> INFO  system - ======================================================================
[2019-09-08T10:29:00,486] <launcher> INFO  system - BASE dir:/usr/local/UniFi
[2019-09-08T10:29:00,589] <launcher> INFO  system - Current System IP: 192.168.1.1
[2019-09-08T10:29:00,589] <launcher> INFO  system - Hostname: pfSense.localdomain
[2019-09-08T10:29:03,736] <launcher> INFO  db     - waiting for db connection...
[2019-09-08T10:29:04,247] <launcher> INFO  db     - Connecting to mongodb://127.0.0.1:27117
[2019-09-08T10:29:07,703] <launcher> INFO  db     - DB version (5.10.25) different from Runtime Version(5.10.26), migrating...
[2019-09-08T10:29:07,720] <launcher> INFO  system - [server backup] started
[2019-09-08T10:29:07,722] <launcher> INFO  db     - Connecting to mongodb://127.0.0.1:27117
[2019-09-08T10:29:09,842] <launcher> ERROR system - Fail to create a backup for version '5.10.25'
[2019-09-08T10:29:09,843] <launcher> ERROR system - Info on backup error is...
com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at com.mongodb.connection.SocketStream.read(SocketStream.java:88) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:494) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:224) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.connection.UsageTrackingInternalConnection.receiveMessage(UsageTrackingInternalConnection.java:96) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection.receiveMessage(DefaultConnectionPool.java:440) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:112) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:176) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:216) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:207) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:113) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:516) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:510) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:435) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:408) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:510) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:81) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.Mongo.execute(Mongo.java:836) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.Mongo$2.execute(Mongo.java:823) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:870) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.DBCursor.hasNext(DBCursor.java:142) ~[mongo-java-driver-3.4.3.jar:?]
	at com.ubnt.service.B.OOoo.o00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.B.OOoo.o00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.B.J.o00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.B.thisnew.new(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.B.O0oo.?00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.B.OOoo.afterPropertiesSet(Unknown Source) ~[ace.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:394) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:366) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$cdf2aa06.dbService(<generated>) ~[ace.jar:?]
	at com.ubnt.service.AppContext.configService(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$cdf2aa06.CGLIB$configService$74(<generated>) ~[ace.jar:?]
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$cdf2aa06$$FastClassBySpringCGLIB$$2fda4297.invoke(<generated>) ~[ace.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$cdf2aa06.configService(<generated>) ~[ace.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:620) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:455) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:394) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:366) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$cdf2aa06.configService(<generated>) ~[ace.jar:?]
	at com.ubnt.service.AppContext.autoOptimizer(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$cdf2aa06.CGLIB$autoOptimizer$40(<generated>) ~[ace.jar:?]
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$cdf2aa06$$FastClassBySpringCGLIB$$2fda4297.invoke(<generated>) ~[ace.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$cdf2aa06.autoOptimizer(<generated>) ~[ace.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:620) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:455) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) [spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) [spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846) [spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) [spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) [spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:88) [spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.ubnt.service.OoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.?o0000(Unknown Source) [ace.jar:?]
	at com.ubnt.service.OoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.?00000(Unknown Source) [ace.jar:?]
	at com.ubnt.ace.Launcher.main(Unknown Source) [ace.jar:?]
[2019-09-08T10:29:09,860] <launcher> INFO  system - [server backup][BACKUP] end
[2019-09-08T10:29:09,877] <launcher> WARN  AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'autoOptimizer' defined in com.ubnt.service.AppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ubnt.service.I.B]: Factory method 'autoOptimizer' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configService' defined in com.ubnt.service.AppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ubnt.service.oOoo.OOOo]: Factory method 'configService' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dbService' defined in com.ubnt.service.AppContext: Invocation of init method failed; nested exception is com.mongodb.MongoSocketReadException: Exception receiving message
[2019-09-08T10:29:09,884] <db-server> INFO  db     - DbServer stopped
[2019-09-08T10:29:09,884] <db-server> WARN  db     - Mongo start up failed with rc=134
[2019-09-08T10:29:09,884] <db-server> WARN  db     - Unknown error, restarting mongo without logging to verify error
[2.4.4-RELEASE][admin@pfSense.localdomain]/usr/local/UniFi/logs/logs:

**Comment by EeroV** [comment]
fixed issue with pruning mongodb database: https://help.ubnt.com/hc/en-us/articles/204911424-UniFi-How-to-Remove-Prune-Older-Data-and-Adjust-Mongo-Database-Size

**Comment by EeroV** [comment]
...
