### ISSUE TITLE
Cannot adopt access point with 4.8.x - Unifi local copy of snappy missing FreeBSD native library

### ISSUE THREAD

**Issue by jeffdoering** [gozoinks/unifi-pfsense#29]
Unifi software 4.8.14 seems to start and work fine after upgrade. However; it cannot adopt my access point.

Turns out that the following error is preventing adoption:

server.log.1:[2016-04-04 16:05:36,869] <launcher> WARN  system - cannot load native lib - ubnt_webrtc_jni
server.log.1:org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=FreeBSD and os.arch=amd64

I resolved this by symlinking the FreeBSD snappy package jar into the Unifi directory. Not sure if something is unique about my setup causing this issue (it worked fine for older releases including if I revert now) or if others are facing the same problem.

**Comment by NorfAlrin** [comment]
I have the same problem with 4.8.14.

**Comment by gozoinks** [comment]
What version of pfSense?

**Comment by NorfAlrin** [comment]
It was present under 2.2.6;
I'm currently in the process of trying to fix it 2.3 but it is taking some time due to the changes to the package manager.

**Comment by NorfAlrin** [comment]
Actually I'm getting a slightly different error but I believe that they are related (see full error log below), The error has remained the same between 2.2.6 and 2.3, but I've upgraded UniFi to V4.9.2 of the controller software in an attempt to fix the adoption fixed, so your mileage may vary with the below.

The fix is to install snappyjava, "pkg install snappyjava"
Backup the old package snappy file /usr/local/UniFi/lib/snappy-java-1.0.5.jar
Simlink or copy the package to from  /usr/local/share/java/classes/snappy-java.jar to /usr/local/UniFi/lib/snappy-java-1.0.5.jar
Then re-start / start Unifi

Others experiencing the issue can be found here.
https://community.ubnt.com/t5/UniFi-Routing-Switching/Unifi-4-6-3-controller-under-freebsd/td-p/1229394

# Error
*[2016-04-16 00:33:09,819] <stat-daily> INFO  system - housekeeper[stat-daily] exception caught
com.mongodb.MongoException: '$set' is empty. You must specify a field like so: {$mod: {<field>: ...}}
        at com.mongodb.CommandResult.getException(CommandResult.java:100)
        at com.mongodb.CommandResult.throwOnError(CommandResult.java:134)
        at com.mongodb.DBTCPConnector._checkWriteError(DBTCPConnector.java:142)
        at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:183)
        at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:155)
        at com.mongodb.DBApiLayer$MyCollection.update(DBApiLayer.java:349)
        at com.mongodb.DBCollection.update(DBCollection.java:177)
        at com.mongodb.DBCollection.update(DBCollection.java:208)
        at com.ubnt.service.OoOO.K.o00000(Unknown Source)
        at com.ubnt.service.OoOO.K.?00000(Unknown Source)
        at com.ubnt.service.OoOO.H.o00000(Unknown Source)
        at com.ubnt.service.OoOO.H.o00000(Unknown Source)
        at com.ubnt.service.OoOO.H$12.run(Unknown Source)
        at com.ubnt.ace.E$_Oo.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)*

**Comment by TribuneX** [comment]
Thanks @NorfAlrin! That fixed my issues!

**Comment by 74kumi** [comment]
I'm running the newest version of pfsense 2.3.1-RELEASE-p1 I've modified the install script to have the newest unifi package  4.8.18. For the most part it runs great I had to fix this issue though but it could very easily be fixed by changing the install script and adding this `fetch http://pkg.freebsd.org/freebsd:10:x86:64/release_1/All/snappyjava-1.0.4.1_1.txz
tar vfx snappyjava-1.0.4.1_1.txz
cp ./usr/local/share/java/classes/snappy-java.jar /usr/local/UniFi/lib/snappy-java-1.0.5.jar`
When this was all done i was able to upgrade both of my APs to the newest firmware and they adopted just fine. So just running those 3 lines of code fixes this issue.

**Comment by gozoinks** [comment]
Sounds great! I wasn't sure how best to proceed. Can you prepare a patch?

On Sat, May 28, 2016 at 9:53 PM, 74kumi <notifications@github.com> wrote:

> I'm running the newest version of pfsense 2.3.1-RELEASE-p1 I've modified
> the install script to have the newest unifi package 4.8.18. For the most
> part it runs great I had to fix this issue though but it could very easily
> be fixed by changing the install script and adding this fetch
> http://pkg.freebsd.org/freebsd:10:x86:64/release_1/All/snappyjava-1.0.4.1_1.txz
> tar vfx snappyjava-1.0.4.1_1.txz
> cp ./usr/local/share/java/classes/snappy-java.jar
> /usr/local/UniFi/lib/snappy-java-1.0.5.jar
> When this was all done i was able to upgrade both of my APs to the newest
> firmware and they adopted just fine. So just running those 3 lines of code
> fixes this issue.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/gozoinks/unifi-pfsense/issues/29#issuecomment-222339787>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABn_sO_oWaU-f-xvzrgJi-4wqKxIGaNjks5qGP-tgaJpZM4IAN69>
> .
>



-- 

j

**Comment by jmcphail** [comment]
Should be resolved in latest pull request.

**Comment by gnkidwell** [comment]
Resolved in earlier merge.
